/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.test.divisorepiano;

import it.cnr.istc.UtilsANN;
import it.cnr.istc.ann.Trainer;
import it.cnr.istc.datasets.Dataset;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import javax.swing.GroupLayout;

/**
 *
 * @author Luca Coraci <luca.coraci@istc.cnr.it> ISTC-CNR
 */
public class LinePanel extends javax.swing.JPanel {

    public List<PointTest> points = new CopyOnWriteArrayList<>();
    public PointTest startLinePoint;
    public PointTest endLinePoint;

    /**
     * Creates new form LinePanel
     */
    public LinePanel() {
        initComponents();
//        for (int i = 0; i < 200; i++) {
//            int x = UtilsANN.generateRandomInRange(0, 800);
//            int y = UtilsANN.generateRandomInRange(0, 800);
//            
//            drawPoint(x, y, x-y>0 ? true : false);
//        }

        this.startLinePoint = new PointTest(0, 0, true);
        this.endLinePoint = new PointTest(-1, -1, true);

    }

    public PointTest getStartLinePoint() {
        return startLinePoint;
    }

    public void setStartLinePoint(PointTest startLinePoint) {
        this.startLinePoint = startLinePoint;
    }

    public PointTest getEndLinePoint() {
        return endLinePoint;
    }

    public void setEndLinePoint(PointTest endLinePoint) {
        this.endLinePoint = endLinePoint;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2d = (Graphics2D) g;

        if (this.endLinePoint.getX() == -1) {
            g2d.drawLine(startLinePoint.getX(), startLinePoint.getY(), this.getWidth(), this.getHeight());
        } else {
            g2d.drawLine(startLinePoint.getX(), startLinePoint.getY(), endLinePoint.getX(), endLinePoint.getY());
        }

//        System.out.println("POINT SIZE: " + points.size());
        for (PointTest point : points) {
            if (point.isOk()) {
                g2d.setPaint(new Color(0, 255, 0));
            } else {
                g2d.setPaint(new Color(255, 0, 0));
            }
            g2d.fillOval(point.getX() - 4, point.getY() - 4, 8, 8);
        }

        g2d.setPaint(new Color(0, 0, 255));
//        int bohx = (int)Trainer.getInstance().getPerceptron().guessY(0);
//        System.out.println("BOHX = "+bohx);
        if (!Beans.isDesignTime()) {
            g2d.drawLine(1, (int) Trainer.getInstance().getPerceptron().guessY(1), 700, (int) Trainer.getInstance().getPerceptron().guessY(700));
        }

    }

    public void drawPoint(int x, int y, boolean ok) {
        this.points.add(new PointTest(x, y, ok));

    }

    public void clearPoints() {
        this.points.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new Color(255, 255, 255));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
