/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.test;

import it.cnr.istc.icv.engine.MixedDataPanel;
import it.cnr.istc.icv.engine.MyJLayer;
import it.cnr.istc.icv.engine.MyLayer;
import it.cnr.istc.icv.engine.ZoomLabeledLayer;
import it.cnr.istc.icv.engine.listeners.CoordinateListener;
import it.cnr.istc.icv.engine.listeners.PopupMenuTriggerListener;
import it.cnr.istc.icv.exceptions.TypeDataMismatchException;
import it.cnr.istc.icv.logic.ICVAnnotation;
import it.cnr.istc.icv.test.LinearDataSupporter;
import it.cnr.istc.icv.test.TimeValueSupporterClass;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToolBar;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author Luca Coraci <luca.coraci@istc.cnr.it> ISTC-CNR
 */
public class QuadranteTester extends javax.swing.JFrame implements CoordinateListener, PopupMenuTriggerListener {

    final static MixedDataPanel panel = new MixedDataPanel();

    /**
     * Creates new form QuadranteTester
     */
    public QuadranteTester() {
        try {
            initComponents();
            panel.addCoordinateListener(this);
            panel.addPopupMenuTriggerListener(this);
            panel.setStartRange(new Date(113, 9, 5, 9, 0, 0).getTime());
            panel.setEndRange(new Date(113, 9, 5, 12, 0, 0).getTime());
            panel.setShowDate(true);
//            panel.setBackgroundChartColor(Color.BLACK);
//            panel.setyAxisDataColor(Color.yellow);
//            panel.setxAxisDataColor(Color.yellow);
            panel.setBackground(Color.WHITE);
//        panel.setDataColor(new Color(0,146,29));
            panel.setZoomEnable(true);

            LinearDataSupporter s = new LinearDataSupporter("MEGA SUPER Error");
//        s.setOrder(1);
            s.setDiscret(true);
            s.setMaxValueToShow(100);
            s.setMinValueToShow(10);
            s.setMaxThresholdPaintable(true);
            s.setMaximumThreshold(50);
            s.setMinThresholdPaintable(true);
            s.setMinimumThreshold(15);
            panel.addDataBar(s);
            MyLayer<JPanel> layerUI = new ZoomLabeledLayer(panel);
            JPanel containerP = new JPanel();
            containerP.setLayout(new GridLayout(0, 1));
            containerP.add(panel);

            MyJLayer<JPanel> jlayer = new MyJLayer<JPanel>(panel, layerUI);
            containerP.add(jlayer);
            this.jScrollPane1.setViewportView(containerP);

            TimeValueSupporterClass ds1 = new TimeValueSupporterClass(23, "Sistolic", new Date(113, 9, 5, 9, 50, 0));
//            s.addData(ds1);
            TimeValueSupporterClass ds2 = new TimeValueSupporterClass(50, "Sistolic", new Date(113, 9, 5, 10, 50, 0));
//            s.addData(ds2);
            TimeValueSupporterClass ds3 = new TimeValueSupporterClass(44, "Sistolic", new Date(113, 9, 5, 11, 10, 0));
//            s.addData(ds3);
            TimeValueSupporterClass ds4 = new TimeValueSupporterClass(40, "Dia", new Date(113, 9, 5, 9, 50, 0));

            panel.addLinearData("MEGA SUPER Error", ds1, false);
            panel.addLinearData("MEGA SUPER Error", ds2, false);
            panel.addLinearData("MEGA SUPER Error", ds3, false);
            panel.addLinearData("MEGA SUPER Error", ds4, false);
        } catch (TypeDataMismatchException ex) {
            Logger.getLogger(QuadranteTester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new JToolBar();
        jScrollPane1 = new JScrollPane();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuadranteTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuadranteTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuadranteTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuadranteTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuadranteTester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane jScrollPane1;
    private JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void currentDate(Date date) {
    }

    @Override
    public void currentValue(Object o) {
    }

    @Override
    public void showTooltip(String string, int i, int i1) {
    }

    @Override
    public void forceFromTo(boolean bln) {
    }

    @Override
    public void rightClickTriggered(String string, Date date, int i, int i1) {
    }

    @Override
    public void rightClickAreaTriggered(String string, ICVAnnotation icva, Date date, int i, int i1) {
    }
}
