/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package it.cnr.istc.test;

import it.cnr.istc.PerceptronTEST;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author Luca Coraci <luca.coraci@istc.cnr.it> ISTC-CNR
 */
public class TestPercetrone extends javax.swing.JFrame {

    PerceptronTEST perceptron = new PerceptronTEST(3);
    boolean currentRed = false;
    /** Creates new form TestPercetrone */
    public TestPercetrone() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new JButton();
        jLabel1 = new JLabel();
        jButton_sbagliato = new JButton();
        jColorChooser1 = new JColorChooser();
        jButton_select = new JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Colore");

        jButton_sbagliato.setText("SBAGLIATO");
        jButton_sbagliato.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_sbagliatoActionPerformed(evt);
            }
        });

        jButton_select.setText("Select");
        jButton_select.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_selectActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jColorChooser1, GroupLayout.PREFERRED_SIZE, 539, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_select))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton_sbagliato, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_sbagliato)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_select))
                    .addComponent(jColorChooser1, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_selectActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_selectActionPerformed
        try {
            Color selectedColor = this.jColorChooser1.getColor();
//            System.out.println("selected color = "+selectedColor);
            float red   = (float)(((selectedColor.getRed() * 100f)/255f)/100);
            float green = (float)(((selectedColor.getGreen() * 100f)/255f)/100);
            float blue  = (float)(((selectedColor.getBlue()* 100f)/255f)/100);
            
//            System.out.println("red = "+red);
//            System.out.println("green = "+green);
//            System.out.println("blue = "+blue);
            perceptron.setInputs(red,green,blue);
            currentRed = perceptron.activate();
            if(currentRed){
                this.jLabel1.setText("ROSSO");
            }else{
                this.jLabel1.setText("NON E' ROSSO");
            }
        } catch (Exception ex) {
            Logger.getLogger(TestPercetrone.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton_selectActionPerformed

    private void jButton_sbagliatoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_sbagliatoActionPerformed

            this.perceptron.adjust(!currentRed);
 
    }//GEN-LAST:event_jButton_sbagliatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestPercetrone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestPercetrone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestPercetrone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestPercetrone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestPercetrone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton2;
    private JButton jButton_sbagliato;
    private JButton jButton_select;
    private JColorChooser jColorChooser1;
    private JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
