/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.cnr.istc.test.nextlevel;

import it.cnr.istc.datasets.DataBucket;
import it.cnr.istc.datasets.Dataset;

/**
 *
 * @author Luca
 */
public class NextLevelTrainer extends javax.swing.JFrame {

    /**
     * Creates new form NextLevelTrainer
     */
    public NextLevelTrainer() {
        initComponents();
    }
    
    private DataBucket generateDataset(){
        
        DataBucket db = new DataBucket(2);
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,0f,1f,1f,1f}, 2));
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,0f,1f,1f,0f}, 1));
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,1f,1f,1f,1f}, 2));
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),1f,1f,1f,0f,0f}, 1));
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,0f,0f,0f,1f}, 1));
        db.addDataset(new Dataset(new float[]{Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,0f,1f,1f,1f}, 2));
        db.addDataset(new Dataset(new float[]{Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),0f,0f,1f,1f,1f}, 3));
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),1f,0f,0f,0f,0f}, 1));
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,0f,1f,1f,1f}, 2));
        db.addDataset(new Dataset(new float[]{Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,1f,1f,1f,1f}, 2));
        db.addDataset(new Dataset(new float[]{Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),Level.EASY.getWeight(),0f,1f,0f,0f,0f}, 1));
        db.addDataset(new Dataset(new float[]{Level.HARD.getWeight(),Level.HARD.getWeight(),Level.HARD.getWeight(),Level.HARD.getWeight(),Level.HARD.getWeight(),0f,0f,1f,1f,1f}, 3));
        db.addDataset(new Dataset(new float[]{Level.HARD.getWeight(),Level.HARD.getWeight(),Level.HARD.getWeight(),Level.HARD.getWeight(),Level.HARD.getWeight(),1f,0f,1f,0f,0f}, 2));
        db.addDataset(new Dataset(new float[]{Level.HARD.getWeight(),Level.HARD.getWeight(),Level.HARD.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),1f,0f,0f,0f,0f}, 2));
        db.addDataset(new Dataset(new float[]{Level.HARD.getWeight(),Level.HARD.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),0f,0f,0f,0f,0f}, 1));
        db.addDataset(new Dataset(new float[]{Level.HARD.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),Level.MEDIUM.getWeight(),0f,0f,1f,1f,0f}, 2));
        
        return db;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("Train");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Test Input");

        jButton2.setText("Test");

        jLabel2.setText("Response:");

        jLabel3.setText("response");

        jButton3.setText("Wrong");

        jButton4.setText("Correct");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            System.out.println("Training.. ");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NextLevelTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NextLevelTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NextLevelTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NextLevelTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NextLevelTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
